### ISSUE TITLE
is_mount() function requires Python 3.7+

### ISSUE THREAD

**Issue by chris91219** [mlsmithjr/transcoder#12]
Great project guys.
When trying to play with the tool I've found an update for the doc - dependencies: Python 3 (3.6 or higher).

So I was installing it on Ubuntu 18.04 and its default python3 ( python 3.6.9 ), running the script will get this error report:

> convertor2@convertor2:~/autotrans$ ~/.local/bin/pytranscoder --dry-run test.mp4
> Exception in thread _default_:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/home/convertor2/.local/lib/python3.6/site-packages/pytranscoder/transcode.py", line 63, in run
>     self.go()
>   File "/home/convertor2/.local/lib/python3.6/site-packages/pytranscoder/transcode.py", line 80, in go
>     if is_mounted(job.inpath) and self.config.fls_path():
>   File "/home/convertor2/.local/lib/python3.6/site-packages/pytranscoder/utils.py", line 89, in is_mounted
>     if str(part) != str(part.root) and part.is_mount():
> AttributeError: 'PosixPath' object has no attribute 'is_mount'

Note that is_mount() from pathlib is available from python 3.7 (https://docs.python.org/3/library/pathlib.html#pathlib.Path.is_mount)

And update to python3.7+ fixed the issue.

**Comment by mlsmithjr** [comment]
Thanks for the clarification. README updated.
