### ISSUE TITLE
how can read rtsp stream with cuda?

### ISSUE THREAD

**Issue by junedgar** [mlsmithjr/transcoder#6]
Hi, thank you for your great work!
I am newer for ffmpeg. 
Can you give me some advice about how can I read rtsp stream in python with hardware acceleration?

**Comment by mlsmithjr** [comment]
I'm not familiar with it, but you might try https://pypi.org/project/rtsp/

**Comment by junedgar** [comment]
@MarshallSmithJr 
thank you for your reply!
